CREATE TABLE USER
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID   VARCHAR(100),
    NAME         VARCHAR(50),
    TOKEN        VARCHAR(36),
    GMT_CREATE   BIGINT,
    GMT_MODIFIED BIGINT
);