CREATE TABLE USER
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID   VARCHAR(100) NOT NULL,
    NAME         VARCHAR(50) NOT NULL,
    TOKEN        VARCHAR(36) NOT NULL,
    GMT_CREATE   BIGINT NOT NULL,
    GMT_MODIFIED BIGINT NOT NULL
);