CREATE TABLE QUESTION
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(50),
    DESCRIPTION TEXT,
    GMT_CREATE BIGINT NOT NULL,
    GMT_MODIFIED BIGINT NOT NULL,
    CREATOR BIGINT NOT NULL,
    COMMENT_COUNT INT DEFAULT 0,
    VIEW_COUNT INT DEFAULT 0,
    LIKE_COUNT INT DEFAULT 0,
    TAG VARCHAR(256)
);

